version: '3.9'
services:
  redis:
    image: melodia/redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis:/var/lib/redis/data
    container_name: redis

volumes:
  redis:
    driver: local
