version: '3.9'

services:
  django:
    build:
      context: django
      dockerfile: Dockerfile
    image: melodia/django:latest
    container_name: django
    depends_on:
      - redis
    ports:
      - 8081:8081
    command: /start

  redis:
    build:
      context: redis
      dockerfile: Dockerfile
    image: melodia/redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis:/var/lib/redis/data
    container_name: redis

volumes:
  redis:
    driver: local