version: '3.9'
services:
  django:
    image: melodia/django:latest
    depends_on:
      - redis
    ports:
      - "8081:8081"
    container_name: django
  redis:
    image: melodia/redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis:/var/lib/redis/data
    container_name: redis

volumes:
  redis:
    driver: local
