##########################################################################################
#
#
#   Este fichero almacena constantes para los errores que se van a devolver con nombres
#   más descriptivos
#
#
##########################################################################################

OK = 200

FORBIDDEN = 403

# No poner errores menores al 515, están reservados para el estandar HTTP
# Constantes para los errores de audios
ERROR_CANCION_NO_ENCONTRADA = 519
ERROR_CANCION_NO_ELIMINADA = 520
ERROR_CANCION_NO_MODIFICADA = 521
ERROR_CANCION_NO_ANYADIDA = 522
ERROR_CANCION_ELEMENTOS_FALTANTES = 523
ERROR_CANCION_ELEMENTOS_VACIOS = 524

ERROR_PODCAST_NO_ENCONTRADO = 525
ERROR_PODCAST_NO_ELIMINADO = 526
ERROR_PODCAST_NO_MODIFICADO = 527
ERROR_PODCAST_NO_ANYADIDO = 528
ERROR_PODCAST_ELEMENTOS_FALTANTES = 529
ERROR_PODCAST_ELEMENTOS_VACIOS = 530

# Constantes para los errores de usuarios
ERROR_USUARIO_NO_ENCONTRADO = 531
ERROR_USUARIO_PARAMETROS_INCORRECTOS = 532
ERROR_CONTRASENYA_INCORRECTA = 533
ERROR_USUARIO_EMAIL_YA_EXISTE = 539
ERROR_USUARIO_NO_ADMINISTRADOR = 540
ERROR_USUARIO_TIPO_NO_VALIDO = 550
ERROR_USUARIO_YA_SUSCRITO = 554
ERROR_USUARIO_NO_SUSCRITO = 555
ERROR_USUARIO_YA_ES_ARTISTA = 557



# Constantes para los errores de listas de reproducción
ERROR_LISTA_NO_ENCONTRADA = 534
ERROR_LISTA_PARAMETROS_INCORRECTOS = 535
ERROR_LISTA_TIPO_INCORRECTO = 551
ERROR_LISTA_PRIVACIDAD_INCORRECTA = 556
ERROR_AUDIO_NOT_IN_LISTA = 552


# Constantes para los errores de notificaciones
ERROR_NOTIFICACION_NO_ENCONTRADA = 536
ERROR_TIPO_NOTIFICACION_NO_VALIDA = 537
ERROR_NOTIFICACION_NO_SOLICITUD_ARTISTA = 541

# Constantes para los errores de administradores y artistas
ERROR_NO_SE_HA_PODIDO_CAMBIAR_TIPO_USUARIO = 538

# Constantes para los errores de carpetas
ERROR_CARPETA_PARAMETROS_INCORRECTOS = 542
ERROR_CARPETA_NO_ENCONTRADA = 543
ERROR_LISTA_NOT_IN_CARPETA = 544
ERROR_CARPETA_NOT_IN_USER = 553

# Constantes para los errores de gestión de amigos
ERROR_USUARIO_YA_AMIGO = 545
ERROR_NOTIFICACION_NO_AMIGO = 546
ERROR_USUARIO_NO_AMIGO = 547